# Pakages custom settings

email: null
username: null
content_type: application/vnd.spack.package

# Default editor to edit config
config_editor: vim

# Default cache_dir unset, meaning created in /tmp
cache_dir: null

# Default registry prefix to install from
trusted_packages_registry: ghcr.io/pakages

# Registries we pull from
trusted_pull_registries:
 - ghcr.io/pakages

# Default tag for pushed artifacts
default_tag: "latest"
