name: linting

on:
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup black linter
      run: conda create --quiet --name black pyflakes

    - name: Lint and format Python code
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate black
        pip install -r .github/dev-requirements.txt
        pre-commit run --all-files
