name: Spack Build

# Spack is done in a container so we control os, version, etc.
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        repo: [["zlib", "https://github.com/pakages/zlib/"]]  
    runs-on: ubuntu-latest
    name: Pakages Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone ${{ matrix.repo[0] }}
        env:
          package: ${{ matrix.repo[0] }}
          repo: ${{ matrix.repo[1] }}
        run: |
          git clone ${repo}
          cd ${package}

      - name: Build and Deploy Spack Package
        env:
          deploy: true
#         deploy: ${{ github.event_name != 'pull_request' }}
          package: ${{ matrix.repo[0] }}
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/pakages
        run: /entrypoint.sh
