name: Spack Build

# Spack is done in a container so we control os, version, etc.
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: ["zlib"]
    runs-on: ubuntu-latest
    name: Pakages Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files
        run: ls .
      - name: Build and Deploy Spack Package
        env:
          deploy: true
#         deploy: ${{ github.event_name != 'pull_request' }}
          package: ${{ matrix.package }}
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/pakages
        run: /bin/bash entrypoint.sh
