name: Spack Build

# Spack is done in a container so we control os, version, etc.
on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: ["zlib"]
    runs-on: ubuntu-latest
    name: Pakages Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python Environment
        run: |
          conda create --quiet --name pak requests
          echo "/usr/share/miniconda/bin" >> $GITHUB_PATH
          echo "/usr/share/miniconda/envs/pak/bin" >> $GITHUB_PATH

      - name: Install pakages and Spack
        run: |
           git clone --depth 1 https://github.com/spack/spack /tmp/spack
           echo "/tmp/spack/bin" >> $GITHUB_PATH
           source activate pak
           pip install -e .[all]
           pip install pytest

      - name: Test Spack
        run: |
          source activate pak
          pytest -xs tests/test_spack.py

      - name: List Files
        run: ls .
      - name: Build and Deploy Spack Package
        env:
          deploy: ${{ github.event_name != 'pull_request' }}
          package: ${{ matrix.package }}
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/syspack/pakages
        run: |
           source activate pak
           /bin/bash entrypoint.sh
