name: test-action

on:
  pull_request: []

jobs:
  test-action:
    name: Test Build Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pakages
        run: pip install -e .[all]

      - name: Test Pakages Build
        uses: ./action/build
        with:
          target: ghcr.io/syspack/pakages-bundle:latest
