name: Spack Build

# Spack is done in a container so we control os, version, etc.
on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: ["zlib"]
    runs-on: ubuntu-latest
    name: Pakages Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pakages and Spack
        run: |
           git clone --depth 1 https://github.com/spack/spack /tmp/spack
           pip install -e .[all]
           pip install pytest

      - name: Test Spack
        run: |
          export PATH=/tmp/spack/bin:$PATH
          pytest -xs tests/test_spack.py

      - name: List Files
        run: ls .
      - name: Build and Deploy Spack Package
        env:
          deploy: ${{ github.event_name != 'pull_request' }}
          package: ${{ matrix.package }}
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/syspack/pakages
        run: |
          export PATH=/tmp/spack/bin:$PATH
          /bin/bash entrypoint.sh
